### ISSUE TITLE
Payment module and improvements

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/roadmap#5]
We are working on improving the payments domain to allow for more advanced use cases such as native split payments.

The payment functionality and new changes will be introduced in a new package, `@medusajs/payment`. This package is generic to the extent of allowing developers to associate payment functionality with any other and their own features.

The high-level payment flows will not change much. It is primarily the underlying architecture as well as the data models that will.

**Comment by toooo** [comment]
Hi
Is this issue connected with:
https://github.com/medusajs/medusa/discussions/2851

What is the best way to start developing new payment gateway now? Or to wait until this is finished?

**Comment by olivermrbl** [comment]
@toooo, the checkout API will likely come in a follow up iteration to the payment module.

The interface for the payment processor will not see major changes, so you can follow our docs [here](https://docs.medusajs.com/modules/carts-and-checkout/backend/add-payment-provider). 

When V2 releases, we will include a guide on how to get it up to speed.

**Comment by JCheungX** [comment]
@olivermrbl just wondering if this module will be release earlier similar to other individual module or this one has to wait 2.0?
I am looking into the capability to split payment and do deposit. 
I can probably do this via custom cart completion strategy. I was thinking if this module release earlier then maybe i can do it the proper way instead of doing custom cart completion strategy.

**Comment by rakibatomnixima** [comment]
@olivermrbl can we have native integration for subscription based payment?

**Comment by TALHA0713** [comment]
Hi, I need some help i want to integrate the online custom payment gateway which works in Pakistan 
is there any plugin create which works in pakistan currency
